### ISSUE TITLE
Create Dummy Data for Customer End of the API

### ISSUE THREAD

**Issue by BlaiseRoberts** [solanum-tuberosums/bangazonOrientationAPI#23]
## Associated Ticket
- [ERD](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/6)

### Description
Dummy data needs to be inserted into our fixtures folder so everyone can loaddata to keep everyone's data consistent.

### Recommended Solution
Run the dumpdata commands to create the json file after posting data to our API.

**Comment by willsims14** [comment]
DummyData = ```api/fixtures/customerdata.json```
