### ISSUE TITLE
Dummy Data is No Longer Valid After Editorial Adjustments to models, views, and serializers

### ISSUE THREAD

**Issue by JeremyBakker** [solanum-tuberosums/bangazonOrientationAPI#50]
## Associated Ticket
- ~~[Create Dummy Data for the Customer End of the API](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/23)~~
- ~~[Create Dummy Data for the Business End of the API](https://github.com/solanum-tuberosums/bangazonOrientationAPI/issues/40)~~

### Expected Behavior
All tables should populate when command is run

### Steps to Reproduce
- Delete ```bangaon/api/migrations/```
- Delete ```db.sqlite3```
- Run this: ```python manage.py builddb```

**Comment by ANMyers** [comment]
Issue has been resolved sir.
