### ISSUE TITLE
Create the ERD

### ISSUE THREAD

**Issue by JeremyBakker** [solanum-tuberosums/bangazonOrientationAPI#6]
## Associated Ticket
NONE

### Description
Create the ERD.

### Recommended Solution
Create a basic ERD in draw.io that represents all the resources from the [README](https://github.com/solanum-tuberosums/bangazonOrientationAPI/blob/master/README.md):

Customer
Order
Product
Department
Computer
Training Program
Product Type
Payment Type
Employee

NOTE: Export the file from draw.io and upload it to the github root directory when complete.

**Comment by willsims14** [comment]
ERD is NOT final.
